# Generated by Django 5.1.2 on 2024-10-23 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarios',
            name='cod',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
