# Generated by Django 5.1.2 on 2024-10-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios_app', '0003_rename_nombre_diarios_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarios',
            name='pre_visualizacion',
            field=models.ImageField(blank=True, null=True, upload_to='pre-visualizacion/'),
        ),
    ]
