# Generated by Django 5.1.3 on 2024-11-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios_app', '0005_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('codigo', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='diarios',
            name='disponibilidad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diarios_app.diariodisponibilidad'),
        ),
    ]
