# Generated by Django 5.1.1 on 2024-12-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios_app', '0007_alter_historial_unique_together_diariosolicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodisponibilidad',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='diariodisponibilidad',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diarios',
            name='cod',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='diarios',
            name='disponibilidad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diario', to='diarios_app.diariodisponibilidad'),
        ),
        migrations.AlterField(
            model_name='diarios',
            name='localidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='diarios',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
